version: "3.9"
services:
  web:
    build: .
    ports:
      - "8080:5000"
    environment:
      - DBNAME="postgres"
      - DBHOST="postgres:13"
      - DBUSER="postgres"
      - DBPASS="sa"
      - DBPORT="6001"
      - API_URL=""
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB="postgres"
      - POSTGRES_USER="postgres"
      - POSTGRES_PASSWORD="sa"
      - POSTGRES_HOST="postgres:13"
      - POSTGRES_PORT="6001"
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
